// This file is generated by Astro DB
declare module 'astro:db' {
	export const Project: import("@astrojs/db/runtime").Table<
		"Project",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Project","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Project","primaryKey":false,"optional":false}},"description":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"description","collection":"Project","primaryKey":false,"optional":false}},"image":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"image","collection":"Project","primaryKey":false,"optional":false}},"link":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"link","collection":"Project","primaryKey":false,"optional":false}},"tags":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"tags","collection":"Project","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"Project"}}}
	>;
	export const BlogPost: import("@astrojs/db/runtime").Table<
		"BlogPost",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"BlogPost","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"BlogPost","primaryKey":false,"optional":false}},"content":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"content","collection":"BlogPost","primaryKey":false,"optional":false}},"image":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"image","collection":"BlogPost","primaryKey":false,"optional":false}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"BlogPost"}}}
	>;
	export const Admin: import("@astrojs/db/runtime").Table<
		"Admin",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Admin","primaryKey":true}},"username":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"username","collection":"Admin","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"Admin","primaryKey":false,"optional":false}}}
	>;
}
